/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.Scanner;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class examen2_p2_miguelmoran extends javax.swing.JFrame {

    File file = new File("fabrica.txt");
    int elementos = 0;
    ArrayList<Etapa> etapas = new ArrayList<>();
    
    public examen2_p2_miguelmoran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ensamblaje_progress = new javax.swing.JProgressBar();
        Pintura_progress = new javax.swing.JProgressBar();
        Empaquetado_Progress = new javax.swing.JProgressBar();
        Iniciar_btn = new javax.swing.JButton();
        Cargar_btn = new javax.swing.JButton();
        Ensamblaje_lbl = new javax.swing.JLabel();
        Pintura_lbl = new javax.swing.JLabel();
        Empaquetado_lbl = new javax.swing.JLabel();
        Ciclo_progress = new javax.swing.JProgressBar();
        Ciclo_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Iniciar_btn.setText("Iniciar");
        Iniciar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar_btnActionPerformed(evt);
            }
        });

        Cargar_btn.setText("Cargar Archivo");
        Cargar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cargar_btnActionPerformed(evt);
            }
        });

        Ensamblaje_lbl.setText("Ensamblaje:");

        Pintura_lbl.setText("Pintura:");

        Empaquetado_lbl.setText("Empaquetado:");

        Ciclo_lbl.setText("Ciclo Dia/Noche:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Ensamblaje_lbl)
                        .addComponent(Empaquetado_lbl)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Iniciar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                            .addComponent(Cargar_btn))
                        .addComponent(Empaquetado_Progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pintura_progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ensamblaje_progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pintura_lbl)
                        .addComponent(Ciclo_progress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Ciclo_lbl))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(Ciclo_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ciclo_progress, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ensamblaje_lbl)
                .addGap(18, 18, 18)
                .addComponent(Ensamblaje_progress, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pintura_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pintura_progress, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Empaquetado_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Empaquetado_Progress, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Iniciar_btn)
                    .addComponent(Cargar_btn))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cargar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cargar_btnActionPerformed
        try {
            Scanner entrada = new Scanner(file);
            while(entrada.hasNextLine()){
                String[] info = entrada.nextLine().split(",");
                Etapa etapa = new Etapa(info[0], Integer.parseInt(info[1]), Integer.parseInt(info[2])*1000);
                etapas.add(etapa);
            }
        } catch (FileNotFoundException ex) {
        }
    }//GEN-LAST:event_Cargar_btnActionPerformed

    private void Iniciar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar_btnActionPerformed
        Thread ensamble = new Thread(){
            public void run(){
                try {
                    Thread.sleep(etapas.get(0).getTiempo());
                } catch (InterruptedException ex) {
                }
                elementos += 1;
                Ensamblaje_progress.setValue(elementos*etapas.get(0).getUnidades()/100);
            }
        };
        Thread pintura = new Thread(){
            public void run(){
                try {
                    Thread.sleep(etapas.get(1).getTiempo());
                } catch (InterruptedException ex) {
                }
                Ensamblaje_progress.setValue(elementos*etapas.get(0).getUnidades()/100);
            }
        };
        Thread Ciclo = new Thread(){
            public void run(){
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException ex) {
                }
                if(Thread.interrupted()){
                    
                } else {
                    ensamble.start();
                }
            }
        };
        Ciclo.start();
    }//GEN-LAST:event_Iniciar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(examen2_p2_miguelmoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(examen2_p2_miguelmoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(examen2_p2_miguelmoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(examen2_p2_miguelmoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new examen2_p2_miguelmoran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cargar_btn;
    private javax.swing.JLabel Ciclo_lbl;
    private javax.swing.JProgressBar Ciclo_progress;
    private javax.swing.JProgressBar Empaquetado_Progress;
    private javax.swing.JLabel Empaquetado_lbl;
    private javax.swing.JLabel Ensamblaje_lbl;
    private javax.swing.JProgressBar Ensamblaje_progress;
    private javax.swing.JButton Iniciar_btn;
    private javax.swing.JLabel Pintura_lbl;
    private javax.swing.JProgressBar Pintura_progress;
    // End of variables declaration//GEN-END:variables
}
